#!/usr/bin/env sh

if [ -z "$1" ]
then
    echo "Language is not specified"
    exit 1
fi

out_folder=./$1_gen/

echo "Generating [$1] code..."
if [ "$1" == "python" ]
then
    python -m grpc_tools.protoc \
        -I./protos \
        --python_out=$out_folder \
        --grpc_python_out=$out_folder \
        ./protos/*
fi

if [ $? -ne 0 ]
then
    exit $?
fi

echo "Done!"
